root: true

parser: "@babel/eslint-parser"
parserOptions:
  ecmaVersion: 2017
  sourceType: "module"

  extends:
  - airbnb-base
  - import-warnings

env:
  browser: true
  node: true
  es6: true
  mocha: true

rules:
  # semis begone
  semi: [2, 'never']
